import { SongMetadata } from "@/dto/SongMetadata";

export const mockSongs: SongMetadata[] = [
  {
    id: "1",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    year: 1975,
    genre: "Rock",
    duration: "5:55",
    trackNumber: 11,
    bitrate: "320 kbps",
    fileSize: "14.2 MB",
    path: "/music/queen/bohemian_rhapsody.mp3",
  },
  {
    id: "2",
    title: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
    year: 1982,
    genre: "Pop",
    duration: "4:54",
    trackNumber: 6,
    bitrate: "320 kbps",
    fileSize: "11.8 MB",
    path: "/music/michael_jackson/billie_jean.mp3",
  },
  {
    id: "3",
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    album: "Nevermind",
    year: 1991,
    genre: "Grunge",
    duration: "5:01",
    trackNumber: 1,
    bitrate: "320 kbps",
    fileSize: "12.1 MB",
    path: "/music/nirvana/smells_like_teen_spirit.mp3",
  },
  {
    id: "4",
    title: "Yesterday",
    artist: "The Beatles",
    album: "Help!",
    year: 1965,
    genre: "Rock",
    duration: "2:05",
    trackNumber: 13,
    bitrate: "320 kbps",
    fileSize: "5.0 MB",
    path: "/music/beatles/yesterday.mp3",
  },
  {
    id: "5",
    title: "Lose Yourself",
    artist: "Eminem",
    album: "8 Mile Soundtrack",
    year: 2002,
    genre: "Hip Hop",
    duration: "5:26",
    trackNumber: 1,
    bitrate: "320 kbps",
    fileSize: "13.1 MB",
    path: "/music/eminem/lose_yourself.mp3",
  },
  {
    id: "6",
    title: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
    year: 1976,
    genre: "Rock",
    duration: "6:30",
    trackNumber: 3,
    bitrate: "320 kbps",
    fileSize: "15.6 MB",
    path: "/music/eagles/hotel_california.mp3",
  },
  {
    id: "7",
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    album: "Appetite for Destruction",
    year: 1987,
    genre: "Rock",
    duration: "5:56",
    trackNumber: 7,
    bitrate: "320 kbps",
    fileSize: "14.3 MB",
    path: "/music/guns_n_roses/sweet_child_o_mine.mp3",
  },
  {
    id: "8",
    title: "Imagine",
    artist: "John Lennon",
    album: "Imagine",
    year: 1971,
    genre: "Rock",
    duration: "3:04",
    trackNumber: 1,
    bitrate: "320 kbps",
    fileSize: "7.4 MB",
    path: "/music/john_lennon/imagine.mp3",
  },
  {
    id: "9",
    title: "Thriller",
    artist: "Michael Jackson",
    album: "Thriller",
    year: 1982,
    genre: "Pop",
    duration: "5:57",
    trackNumber: 4,
    bitrate: "320 kbps",
    fileSize: "14.3 MB",
    path: "/music/michael_jackson/thriller.mp3",
  },
  {
    id: "10",
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    album: "Led Zeppelin IV",
    year: 1971,
    genre: "Rock",
    duration: "8:02",
    trackNumber: 4,
    bitrate: "320 kbps",
    fileSize: "19.3 MB",
    path: "/music/led_zeppelin/stairway_to_heaven.mp3",
  },
  {
    id: "11",
    title: "Like a Rolling Stone",
    artist: "Bob Dylan",
    album: "Highway 61 Revisited",
    year: 1965,
    genre: "Folk Rock",
    duration: "6:13",
    trackNumber: 1,
    bitrate: "320 kbps",
    fileSize: "14.7 MB",
    path: "/music/bob_dylan/like_a_rolling_stone.mp3"
  },
  {
    id: "12",
    title: "Rolling in the Deep",
    artist: "Adele",
    album: "21",
    year: 2011,
    genre: "Soul",
    duration: "3:49",
    trackNumber: 1,
    bitrate: "320 kbps",
    fileSize: "9.8 MB",
    path: "/music/adele/rolling_in_the_deep.mp3"
  },
  {
    id: "13",
    title: "Take On Me",
    artist: "a-ha",
    album: "Hunting High and Low",
    year: 1985,
    genre: "Synth-pop",
    duration: "3:48",
    trackNumber: 1,
    bitrate: "320 kbps",
    fileSize: "9.7 MB",
    path: "/music/a_ha/take_on_me.mp3"
  },
  {
    id: "14",
    title: "Enter Sandman",
    artist: "Metallica",
    album: "Metallica",
    year: 1991,
    genre: "Heavy Metal",
    duration: "5:31",
    trackNumber: 1,
    bitrate: "320 kbps",
    fileSize: "13.2 MB",
    path: "/music/metallica/enter_sandman.mp3"
  },
  {
    id: "15",
    title: "No Woman, No Cry",
    artist: "Bob Marley & The Wailers",
    album: "Natty Dread",
    year: 1974,
    genre: "Reggae",
    duration: "4:06",
    trackNumber: 4,
    bitrate: "320 kbps",
    fileSize: "10.0 MB",
    path: "/music/bob_marley/no_woman_no_cry.mp3"
  },
  {
    id: "16",
    title: "Hallelujah",
    artist: "Jeff Buckley",
    album: "Grace",
    year: 1994,
    genre: "Alternative Rock",
    duration: "6:53",
    trackNumber: 6,
    bitrate: "320 kbps",
    fileSize: "16.1 MB",
    path: "/music/jeff_buckley/hallelujah.mp3"
  },
  {
    id: "17",
    title: "Toxic",
    artist: "Britney Spears",
    album: "In the Zone",
    year: 2003,
    genre: "Pop",
    duration: "3:20",
    trackNumber: 8,
    bitrate: "320 kbps",
    fileSize: "8.5 MB",
    path: "/music/britney_spears/toxic.mp3"
  },
  {
    id: "18",
    title: "Boulevard of Broken Dreams",
    artist: "Green Day",
    album: "American Idiot",
    year: 2004,
    genre: "Alternative Rock",
    duration: "4:20",
    trackNumber: 5,
    bitrate: "320 kbps",
    fileSize: "10.4 MB",
    path: "/music/green_day/boulevard_of_broken_dreams.mp3"
  },
  {
    id: "19",
    title: "Hey Ya!",
    artist: "Outkast",
    album: "Speakerboxxx/The Love Below",
    year: 2003,
    genre: "Hip Hop",
    duration: "3:55",
    trackNumber: 7,
    bitrate: "320 kbps",
    fileSize: "9.9 MB",
    path: "/music/outkast/hey_ya.mp3"
  },
  {
    id: "20",
    title: "Clocks",
    artist: "Coldplay",
    album: "A Rush of Blood to the Head",
    year: 2002,
    genre: "Alternative Rock",
    duration: "5:07",
    trackNumber: 5,
    bitrate: "320 kbps",
    fileSize: "12.3 MB",
    path: "/music/coldplay/clocks.mp3"
  },
  {
    id: "21",
    title: 'Under Pressure',
    artist: 'Queen & David Bowie',
    album: 'Hot Space',
    year: 1981,
    genre: 'Rock',
    duration: '4:08',
    trackNumber: 1,
    bitrate: '320 kbps',
    fileSize: '9.9 MB',
    path: '/music/queen/under_pressure.mp3'
  },
  {
    id: "22",
    title: 'Rolling with the Times',
    artist: 'The Black Keys',
    album: 'Dropout Boogie',
    year: 2022,
    genre: 'Blues Rock',
    duration: '3:58',
    trackNumber: 3,
    bitrate: '320 kbps',
    fileSize: '9.6 MB',
    path: '/music/the_black_keys/rolling_with_the_times.mp3'
  },
  {
    id: "23",
    title: 'Someone Like You',
    artist: 'Adele',
    album: '21',
    year: 2011,
    genre: 'Pop',
    duration: '4:45',
    trackNumber: 11,
    bitrate: '320 kbps',
    fileSize: '11.4 MB',
    path: '/music/adele/someone_like_you.mp3'
  },
  {
    id: "24",
    title: 'Paranoid Android',
    artist: 'Radiohead',
    album: 'OK Computer',
    year: 1997,
    genre: 'Alternative Rock',
    duration: '6:23',
    trackNumber: 2,
    bitrate: '320 kbps',
    fileSize: '15.1 MB',
    path: '/music/radiohead/paranoid_android.mp3'
  },
  {
    id: "25",
    title: 'Creep',
    artist: 'Radiohead',
    album: 'Pablo Honey',
    year: 1993,
    genre: 'Alternative Rock',
    duration: '3:58',
    trackNumber: 2,
    bitrate: '320 kbps',
    fileSize: '9.7 MB',
    path: '/music/radiohead/creep.mp3'
  },
]
