import { SongMetadata } from "@/dto/SongMetadata";

export const mockSongs: SongMetadata[] = [
  {
    id: "1",
    title: "Bohemian Rhapsody",
    artists: ["Queen"],
    albumArtist: "Queen",
    albums: ["A Night at the Opera"],
    years: [1975],
    genres: ["Rock", "Progressive Rock"],
    trackNumber: 11,
    discNumber: 1,
    duration: "5:55",
    bitrate: "320 kbps",
    sampleRate: "44.1 kHz",
    channels: 2,
    encoder: "LAME 3.100",
    fileSize: "14.2 MB",
    composers: ["Freddie Mercury"],
    conductors: [],
    publisher: "EMI",
    copyright: "© 1975 Queen Productions Ltd.",
    isrc: "GBUM71029604",
    bpm: 72,
    key: "Bb",
    mood: "Dramatic",
    language: "English",
    comments: "Epic rock opera",
    lyrics: "Is this the real life? Is this just fantasy?...",
    paths: ["/music/queen/bohemian_rhapsody.mp3"],
    lastModified: "2023-05-15",
    playCount: 42,
    rating: 5,
  },
  {
    id: "2",
    title: "Billie Jean",
    artists: ["Michael Jackson"],
    albumArtist: "Michael Jackson",
    albums: ["Thriller"],
    years: [1982],
    genres: ["Pop", "R&B"],
    trackNumber: 6,
    discNumber: 1,
    duration: "4:54",
    bitrate: "320 kbps",
    sampleRate: "44.1 kHz",
    channels: 2,
    encoder: "LAME 3.100",
    fileSize: "11.8 MB",
    composers: ["Michael Jackson"],
    conductors: [],
    publisher: "Epic Records",
    copyright: "© 1982 MJJ Productions Inc.",
    isrc: "USSM19902983",
    bpm: 117,
    key: "F# minor",
    mood: "Groovy",
    language: "English",
    comments: "Iconic bassline",
    lyrics: "She was more like a beauty queen from a movie scene...",
    paths: ["/music/michael_jackson/billie_jean.mp3"],
    lastModified: "2023-06-20",
    playCount: 38,
    rating: 5,
  },
  {
    id: "3",
    title: "Smells Like Teen Spirit",
    artists: ["Nirvana"],
    albumArtist: "Nirvana",
    albums: ["Nevermind"],
    years: [1991],
    genres: ["Grunge", "Alternative Rock"],
    trackNumber: 1,
    discNumber: 1,
    duration: "5:01",
    bitrate: "320 kbps",
    sampleRate: "44.1 kHz",
    channels: 2,
    encoder: "LAME 3.100",
    fileSize: "12.1 MB",
    composers: ["Kurt Cobain", "Dave Grohl", "Krist Novoselic"],
    conductors: [],
    publisher: "DGC Records",
    copyright: "© 1991 Geffen Records",
    isrc: "USGF19942012",
    bpm: 116,
    key: "F",
    mood: "Angsty",
    language: "English",
    comments: "Grunge anthem",
    lyrics: "Load up on guns, bring your friends...",
    paths: ["/music/nirvana/smells_like_teen_spirit.mp3"],
    lastModified: "2023-04-10",
    playCount: 27,
    rating: 4,
  },
  {
    id: "4",
    title: "Yesterday",
    artists: ["The Beatles"],
    albumArtist: "The Beatles",
    albums: ["Help!"],
    years: [1965],
    genres: ["Rock", "Folk Rock"],
    trackNumber: 13,
    discNumber: 1,
    duration: "2:05",
    bitrate: "320 kbps",
    sampleRate: "44.1 kHz",
    channels: 2,
    encoder: "LAME 3.100",
    fileSize: "5.0 MB",
    composers: ["John Lennon", "Paul McCartney"],
    conductors: ["George Martin"],
    publisher: "Parlophone",
    copyright: "© 1965 Northern Songs",
    isrc: "GBAYE0601477",
    bpm: 94,
    key: "F",
    mood: "Melancholic",
    language: "English",
    comments: "Most covered song in history",
    lyrics: "Yesterday, all my troubles seemed so far away...",
    paths: ["/music/beatles/yesterday.mp3"],
    lastModified: "2023-03-05",
    playCount: 31,
    rating: 5,
  },
  {
    id: "5",
    title: "Lose Yourself",
    artists: ["Eminem"],
    albumArtist: "Eminem",
    albums: ["8 Mile Soundtrack"],
    years: [2002],
    genres: ["Hip Hop", "Rap"],
    trackNumber: 1,
    discNumber: 1,
    duration: "5:26",
    bitrate: "320 kbps",
    sampleRate: "44.1 kHz",
    channels: 2,
    encoder: "LAME 3.100",
    fileSize: "13.1 MB",
    composers: ["Marshall Mathers", "Luis Resto", "Jeff Bass"],
    conductors: [],
    publisher: "Shady Records",
    copyright: "© 2002 Aftermath Records",
    isrc: "USIR10211611",
    bpm: 171,
    key: "D minor",
    mood: "Intense",
    language: "English",
    comments: "Oscar-winning song",
    lyrics: "Look, if you had one shot, one opportunity...",
    paths: ["/music/eminem/lose_yourself.mp3"],
    lastModified: "2023-07-12",
    playCount: 45,
    rating: 5,
  },
]
